### ISSUE TITLE
Missing schema files for YCSB and TPCC

### ISSUE THREAD

**Issue by melhindi** [yuxiamit/LitmusDB#3]
Hi, 
the code expects schema files in `dbx1000_logging/benchmarks/` to initialize tables and indexes.
I added the file for YCSB in my fork (PR #1 ). It would be nice if you could also add the corresponding schema file for TPCC.
(Hint: txt files are ignored by `dbx1000_logging/.gitignore` - I guess this is why they were not pushed)

**Comment by yuxiamit** [comment]
Ah! Thanks for catching this. I've uploaded the schema files.

**Comment by melhindi** [comment]
thanks for uploading them!
